name: Percy Visual Tests with DDEV

on:
  pull_request:
    branches:
      - main  # o la rama principal de tu proyecto

jobs:
  visual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker and DDEV
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-tools xdg-utils
          sudo mkdir -p /usr/local/bin
          curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash

      - name: Start DDEV and wait for Drupal site
        run: |
          ddev start
          sleep 30  # Wait for everything to load, adjust if necessary
          ddev describe
          ddev composer install
          ddev import-db --file=database/db.sql
          ddev drush cr
          ddev drush cim -y

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: |
          npm install
          npm install --save-dev @percy/cli
          npx playwright install

      - name: Run Percy Visual Tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npm run test:visual;
